### PR TITLE
Update Sympy to 1.0

### PR DESCRIPTION
**Pull request by asmeurer**
Based on a minimal test, it seems to work. I'm unsure what all should be checked. I also don't know how to test the Sphinx extension, which is the most important part.

### CODE REVIEW

**Comment by asmeurer** [comment]
Also, is automatic deployment only implemented for SymPy Gamma?

**Comment by asmeurer** [comment]
@lidavidm any chance you could review this?

**Comment by lidavidm** [comment]
Sure, I'll try to get to this over the weekend. I'll also take a look at the documentation and see about describing testing.

Automatic deployment is only implemented for Gamma, although it's been so long that I'm not sure if that even works anymore.

**Comment by lidavidm** [comment]
Deployed a test version at http://95.sympy-live-tests.appspot.com/

[Example of some changes from 1.0](http://95.sympy-live-tests.appspot.com/?evaluate=x%20%3D%20Symbol(%27x%27%2C%20positive%3DTrue)%0A%23--%0Aask(Q.positive(x))%0A%23--%0Aask(Q.zero(x)%20%7C%20Q.zero(y)%2C%20Q.zero(x*y))%0A%23--%0Aask(Implies(Q.zero(x)%2C%20Q.zero(x*y)))%0A%23--%0A) (this is very slow...)

Tab completion seems to work, as do the output formats and other options.

**Comment by lidavidm** [comment]
I built the docs locally (example: http://lidavidm.github.io/sympy/). The shell works but the buttons that allow you to run the code are missing, apparently because the syntax highlighting isn't working - I think this is purely an issue on my end.

The `TESTING` file in the repo does describe a few things to check, though it is a little out of date, and does describe how to set up the Sphinx extension for testing.

**Comment by lidavidm** [comment]
Ok, I think the Sphinx extension should still work. For whatever reason, my copy of Sphinx generates different html (it doesn't add the `highlight-python` class). The Sphinx extension has broken, though (or maybe this is Sphinx) - it ignores the first statement in each code block now (you can see this on http://docs.sympy.org/latest/tutorial/calculus.html, for instance) because Sphinx is inserting an empty element in the beginning of each code block.

**Comment by asmeurer** [comment]
Yes, I saw other people reporting that as well. This PR should be irrelevant to it, right? I am +1 to merge and deploy it. 

For the code block thing, is there a quick workaround we can apply to the [docs](https://github.com/sympy/sympy_doc) to fix it?

**Comment by lidavidm** [comment]
Yeah, this PR does not change that problem.

For the code block, I used `sed -i 's/highlight-default/highlight-python/g'` on all the HTML files. This may cause blocks that aren't python to be highlighted, though.

**Comment by lidavidm** [comment]
https://github.com/sympy/sympy-web-static/pull/9

**Comment by asmeurer** [comment]
Let's merge this and deploy it.

**Comment by lidavidm** [comment]
@asmeurer Sorry - I've been pretty busy with finals/preparing to move for the summer. I'll deploy when I get a chance. Do we want to merge the other fixes while we have the chance?

**Comment by asmeurer** [comment]
Yeah, if there are no issues with them.

**Comment by lidavidm** [comment]
Alright, merged the other changes, I'm going to merge this, then follow up with a PR to update the submodule before deploying.

**Comment by lidavidm** [comment]
@asmeurer it's live at http://46-dot-sympy-live-hrd.appspot.com/ (main site is not using this yet) - if it looks good I'll switch it over.

**Comment by asmeurer** [comment]
It only works if I load unsafe scripts, but when I do it seems to be working.

**Comment by lidavidm** [comment]
Yeah, it will absolutely only work with HTTP, not HTTPS, which is annoying. SymPy Live itself is on HTTP, so we should be fine; I'll switch it over.

I think it's a fairly minor change to enable HTTPS support but right now we wouldn't be able to use it anyways.

**Comment by lidavidm** [comment]
Ok, it's live. The docs might need a force refresh before you see the fixes.

**Comment by asmeurer** [comment]
Awesome. Thanks for working on this.

**Pull request merged**
