### PR TITLE
Add warning for different sympy versions

### PR DESCRIPTION
**Pull request by jtoka**
Add warning for different sympy versions. Fixes https://github.com/sympy/sympy/issues/11892.

### CODE REVIEW

**Comment by lidavidm** [comment]
Hi @jtoka, sorry this has taken so long. This looks good! There's a typo (should "Sym**Py**" not "Sympy"), and perhaps the text could be split across 2 lines?

**Comment by jtoka** [comment]
Thanks for taking a look @lidavidm . I made the requested changes. Please have a look at your convenience.

**Comment by lidavidm** [comment]
It's now live. Thank you for your contribution, and again, sorry this took so long!

**Comment by lidavidm** [comment]
Oh - we do have an AUTHORS list, how would you like your name/email to be listed? (Completely optional of course.)

**Pull request merged**
